package com.visionreport.model;

/**
 * Defines the types of reports that can be generated by Vision-Report.
 * <p>
 * Each type can have its own specific template, behavior, and default settings.
 * This enum is the primary entry point for creating a new report.
 * </p>
 *
 * @author Vision-Report Team
 * @version 0.0.1-SNAPSHOT
 * @since 0.0.1
 */
public enum ReportType {

	/**
	 * A report for UI-based test automation, focusing on screenshots and browser
	 * interactions.
	 */
	UI_TESTING("UI Test Automation Report"),

	/**
	 * A report for API test automation, focusing on request/response details.
	 * (Future)
	 */
	API_TESTING("API Test Automation Report"),

	/**
	 * A report for comparing two JSON files, highlighting differences. (Future)
	 */
	JSON_COMPARE("JSON Comparison Report"),

	/**
	 * A report for comparing two XML files, highlighting differences. (Future)
	 */
	XML_COMPARE("XML Comparison Report"),

	/**
	 * A report for comparing two PDF files, highlighting visual differences.
	 * (Future)
	 */
	PDF_COMPARE("PDF Comparison Report");

	private final String defaultTitle;

	/**
	 * Private constructor for associating a default title with each report type.
	 *
	 * @param defaultTitle The default title to use if the user does not specify
	 *                     one.
	 */
	private ReportType(String defaultTitle) {
		this.defaultTitle = defaultTitle;
	}

	/**
	 * Gets the default report title for this report type.
	 *
	 * @return The default report title.
	 */
	public String getDefaultTitle() {
		return defaultTitle;
	}
}